---
config:
  layout: elk
  look: neo
  theme: mc
---
classDiagram
direction TB
    class FORMATION {
	    nom: Chaîne
	    niveau: Chaîne
	    specialite: Chaîne
	    duree_mois: Numérique
	    id: Numérique(PK)
    }
    class APPRENANT {
	    nom: Chaîne
	    prenom: Chaîne
	    email: Chaîne
	    telephone: Chaîne
	    id: Numérique(PK)
    }
    class ENTREPRISE {
	    nom: Chaîne
	    adresse: Chaîne
	    secteur: Chaîne
	    contact_email: Chaîne
	    id: Numérique(PK)
    }
    class TUTEUR_PEDAGOGIQUE {
	    nom: Chaîne
	    prenom: Chaîne
	    email: Chaîne
	    specialite: Chaîne
	    id: Numérique(PK)
    }
    class TUTEUR_ENTREPRISE {
	    nom: Chaîne
	    prenom: Chaîne
	    email: Chaîne
	    fonction: Chaîne
	    id: Numérique(PK)
	    entreprise_id: Numérique(FK)
    }
    class OFFRE_STAGE {
	    titre: Chaîne
	    description: Texte
	    date_debut: Date
	    date_fin: Date
	    competences_requises: Texte
	    remuneration: Numérique
	    id: Numérique(PK)
	    entreprise_id: Numérique(FK)
    }
    class CANDIDATURE {
	    date_soumission: Date
	    statut: Chaîne
	    lettre_motivation: Texte
	    id: Numérique(PK)
	    apprenant_id: Numérique(FK)
	    offre_stage_id: Numérique(FK)
    }
    class STAGE {
	    date_debut: Date
	    date_fin: Date
	    evaluation_entreprise: Texte
	    evaluation_apprenant: Texte
	    rapport_url: Chaîne
	    id: Numérique(PK)
	    apprenant_id: Numérique(FK)
	    offre_stage_id: Numérique(FK)
    }
    class SUPERVISION {
	    id: Numérique(PK)
	    stage_id: Numérique(FK)
	    tuteur_pedagogique_id: Numérique(FK)
    }
    class ENCADREMENT {
	    id: Numérique(PK)
	    stage_id: Numérique(FK)
	    tuteur_entreprise_id: Numérique(FK)
    }
    class APPARTENANCE {
	    id: Numérique(PK)
	    apprenant_id: Numérique(FK)
	    formation_id: Numérique(FK)
    }
    ENTREPRISE "1" -- "0..N" TUTEUR_ENTREPRISE : emploie
    ENTREPRISE "1" -- "0..N" OFFRE_STAGE : propose
    APPRENANT "1" -- "0..N" CANDIDATURE : soumet
    OFFRE_STAGE "1" -- "0..N" CANDIDATURE : reçoit
    APPRENANT "1" -- "0..1" STAGE : effectue
    OFFRE_STAGE "1" -- "0..1" STAGE : correspond_à
    STAGE "0..N" -- "1..N" SUPERVISION : possède
    TUTEUR_PEDAGOGIQUE "1" -- "0..N" SUPERVISION : participe
    STAGE "0..N" -- "1..N" ENCADREMENT : possède
    TUTEUR_ENTREPRISE "1" -- "0..N" ENCADREMENT : participe
    APPRENANT "0..N" -- "1..N" APPARTENANCE : possède
    FORMATION "1" -- "0..N" APPARTENANCE : inclut
